# Generated by Django 6.0.3 on 2026-04-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('TI', 'TI'), ('Financeiro', 'Financeiro'), ('RH', 'RH'), ('Comercial', 'Comercial'), ('Fiscal', 'Fiscal'), ('Contábil', 'Contábil'), ('Marketing', 'Marketing'), ('Pessoal', 'Pessoal'), ('Empresarial', 'Empresarial'), ('Processos', 'Processos'), ('CSI', 'CSI')], max_length=50)),
                ('type', models.CharField(choices=[('IA', 'IA'), ('Automação', 'Automação'), ('Power Automate', 'Power Automate')], max_length=50)),
                ('time_before', models.PositiveIntegerField()),
                ('time_after', models.PositiveIntegerField()),
                ('implementation_date', models.DateField()),
                ('responsible', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Ativa', 'Ativa'), ('Em Desenvolvimento', 'Em Desenvolvimento'), ('Pausada', 'Pausada')], default='Ativa', max_length=30)),
            ],
            options={
                'ordering': ['-implementation_date', '-id'],
            },
        ),
    ]
